import type { QueryClient } from '@tanstack/react-query';
import type { FinancialChangeDomain } from '@/lib/types';

/**
 * One dependency policy for durable server changes. Keep these query roots in
 * sync with queryKeys in queries.ts; every match is additionally user-scoped.
 */
export const FINANCIAL_CHANGE_QUERY_ROOTS: Record<FinancialChangeDomain, readonly string[]> = {
  activity: [
    'transactions',
    'transactionSplits',
    'summary',
    'transferMatchCandidates',
    'workspace',
    'monthlySnapshot',
    'merchants',
    'categoryIntelligence',
    'budgets',
    'insights',
    'anomalySamples',
    'goals',
    'guidanceBrief',
    'accountPosition',
    'accounts',
    'cashPocketBalance',
    'netWorth',
    'cashPlan',
    'cardOverview',
    'balanceForecast',
    'cardDueRunway',
    'temporalEvents',
    'intelligenceReadiness',
    'reconciliationQuality',
    'learnedMerchantRules',
    'subscriptionReview',
  ],
  today: [
    'workspace',
    'monthlySnapshot',
    'horizon',
    'guidanceBrief',
    'goals',
    'cashPlan',
    'commitments',
    'reserves',
    'liabilities',
    'liabilitySchedule',
    'liabilityOverview',
    'bills',
    'cardOverview',
    'cardDueRunway',
    'cardPortfolioUpcoming',
    'cardPortfolioPaymentPlan',
    'balanceForecast',
    'netWorth',
  ],
  insights: [
    'insights',
    'monthlySnapshot',
    'anomalyAdjudications',
    'anomalySamples',
    'categoryIntelligence',
    'goals',
    'intelligenceReadiness',
    'reconciliationQuality',
    'subscriptionReview',
  ],
  accounts: [
    'accounts',
    'accountIdentityHistory',
    'accountLinkRules',
    'netWorth',
    'cashPlan',
    'cashPocketBalance',
    'accountPosition',
    'balanceForecast',
    'balanceForecastSnapshots',
    'balanceForecastOutcomes',
    'balanceReconciliations',
    'balanceProviderStatus',
    'balanceProviderConnections',
    'balanceProviderMappings',
    'balanceProviderDiscoveredAccounts',
    'cardOverview',
    'cardDueRunway',
    'cardUtilizationHistory',
    'liabilityOverview',
  ],
  cards: [
    'cardOverview',
    'horizon',
    'cardDueRunway',
    'cardUtilizationHistory',
    'cardPortfolioUpcoming',
    'cardPortfolioPaymentPlan',
    'accounts',
    'cardDisputes',
    'accountPosition',
    'netWorth',
    'cashPlan',
    'balanceForecast',
    'liabilities',
    'liabilityOverview',
    'commitments',
    'transactions',
    'transactionSplits',
    'summary',
    'workspace',
    'monthlySnapshot',
    'guidanceBrief',
  ],
  planning: [
    'cashPlan',
    'horizon',
    'commitments',
    'reserves',
    'liabilities',
    'liabilityOverview',
    'liabilitySchedule',
    'payoffComparison',
    'bills',
    'goals',
    'workspace',
    'monthlySnapshot',
    'guidanceBrief',
    'cardOverview',
    'cardDisputes',
    'cardDueRunway',
    'cardPortfolioPaymentPlan',
    'accounts',
    'netWorth',
    'balanceForecast',
    'subscriptionReview',
  ],
  guidance: ['guidanceBrief', 'guidance', 'workspace', 'goals'],
  statements: [
    'statementReview',
    'statementAnalysisReviews',
    'depositStatementReview',
    'transactionSplits',
    'transactions',
    'summary',
    'workspace',
    'monthlySnapshot',
    'insights',
    'accounts',
    'accountPosition',
    'netWorth',
    'cardOverview',
    'cardDueRunway',
    'cashPocketBalance',
    'cashPlan',
    'commitments',
    'liabilities',
    'liabilityOverview',
    'guidanceBrief',
  ],
  data: [
    'job',
    'emails',
    'syncStatus',
    'autoSyncStatus',
    'pipelineMetrics',
    'pipelineFailures',
    'healthChecklist',
    'sourceCoverage',
    'monthlySnapshot',
    'statementAnalysisReviews',
    'statementReview',
    'depositStatementReview',
    'learnedMerchantRules',
  ],
};

export async function invalidateFinancialChangeDomains(
  queryClient: QueryClient,
  userId: string,
  domains: readonly string[],
): Promise<void> {
  if (!userId || domains.length === 0) return;

  const roots = new Set<string>();
  let unknownDomain = false;
  for (const domain of domains) {
    if (!Object.prototype.hasOwnProperty.call(FINANCIAL_CHANGE_QUERY_ROOTS, domain)) {
      unknownDomain = true;
      continue;
    }
    for (const root of FINANCIAL_CHANGE_QUERY_ROOTS[domain as FinancialChangeDomain]) {
      roots.add(root);
    }
  }

  await queryClient.invalidateQueries({
    predicate: (query) =>
      query.queryKey.includes(userId) && (unknownDomain || roots.has(String(query.queryKey[0]))),
  });
}
